/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Meu computador
 */
public class CalcForm extends javax.swing.JFrame {

    /**
     * Creates new form CalcForm
     */
    public CalcForm() {
        initComponents();
    }
    
    Double n1, n2, n3;
    String op, aux;
    String type = "dec"; // base numerica
    Double[] hist = new Double[100];
    int histN=0, x1;
    Excessao f = new Excessao();
    Operacao funct = new Operacao();
    boolean e = true, ini = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResultado = new javax.swing.JTextField();
        jButtonN9 = new javax.swing.JButton();
        jButtonN8 = new javax.swing.JButton();
        jButtonPot = new javax.swing.JButton();
        jButtonFat = new javax.swing.JButton();
        jButtonSqr = new javax.swing.JButton();
        jButtonN4 = new javax.swing.JButton();
        jButtonN5 = new javax.swing.JButton();
        jButtonN6 = new javax.swing.JButton();
        jButtonPi = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jButtonN1 = new javax.swing.JButton();
        jButtonN2 = new javax.swing.JButton();
        jButtonN3 = new javax.swing.JButton();
        jButtonSin = new javax.swing.JButton();
        jButtonCos = new javax.swing.JButton();
        jButtonTan = new javax.swing.JButton();
        jButtonN0 = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonDec = new javax.swing.JButton();
        jButtonNo = new javax.swing.JButton();
        jButtonPorc = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonSub = new javax.swing.JButton();
        jButtonCe = new javax.swing.JButton();
        jButtonBin = new javax.swing.JButton();
        jButtonRound = new javax.swing.JButton();
        jButtonRaiz = new javax.swing.JButton();
        jButtonMul = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonRad = new javax.swing.JButton();
        jButtonEq = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonN7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jBack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemAjuda = new javax.swing.JMenuItem();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        txtResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.setText("0");
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        jButtonN9.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN9.setText("9");
        jButtonN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN9ActionPerformed(evt);
            }
        });

        jButtonN8.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN8.setText("8");
        jButtonN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN8ActionPerformed(evt);
            }
        });

        jButtonPot.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonPot.setText("n^x");
        jButtonPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotActionPerformed(evt);
            }
        });

        jButtonFat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonFat.setText("n!");
        jButtonFat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFatActionPerformed(evt);
            }
        });

        jButtonSqr.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSqr.setText("√n");
        jButtonSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSqrActionPerformed(evt);
            }
        });

        jButtonN4.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN4.setText("4");
        jButtonN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN4ActionPerformed(evt);
            }
        });

        jButtonN5.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN5.setText("5");
        jButtonN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN5ActionPerformed(evt);
            }
        });

        jButtonN6.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN6.setText("6");
        jButtonN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN6ActionPerformed(evt);
            }
        });

        jButtonPi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonPi.setText("π");
        jButtonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiActionPerformed(evt);
            }
        });

        jButtonLog.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonLog.setText("log");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });

        jButtonMod.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonMod.setText("MOD");
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jButtonN1.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN1.setText("1");
        jButtonN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN1ActionPerformed(evt);
            }
        });

        jButtonN2.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN2.setText("2");
        jButtonN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN2ActionPerformed(evt);
            }
        });

        jButtonN3.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN3.setText("3");
        jButtonN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN3ActionPerformed(evt);
            }
        });

        jButtonSin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSin.setText("SIN");
        jButtonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinActionPerformed(evt);
            }
        });

        jButtonCos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonCos.setText("COS");
        jButtonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosActionPerformed(evt);
            }
        });

        jButtonTan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonTan.setText("TAN");
        jButtonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanActionPerformed(evt);
            }
        });

        jButtonN0.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN0.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN0.setText("0");
        jButtonN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN0ActionPerformed(evt);
            }
        });

        jButtonDot.setBackground(new java.awt.Color(153, 153, 153));
        jButtonDot.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonDot.setText(",");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });

        jButtonDec.setBackground(new java.awt.Color(153, 153, 153));
        jButtonDec.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonDec.setText("DEC");
        jButtonDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecActionPerformed(evt);
            }
        });

        jButtonNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonNo.setText("+ | -");
        jButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoActionPerformed(evt);
            }
        });

        jButtonPorc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonPorc.setText("%");
        jButtonPorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorcActionPerformed(evt);
            }
        });

        jButtonPlus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonSub.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSub.setText("-");
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });

        jButtonCe.setBackground(new java.awt.Color(153, 153, 153));
        jButtonCe.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCe.setText("CE");
        jButtonCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCeActionPerformed(evt);
            }
        });

        jButtonBin.setBackground(new java.awt.Color(153, 153, 153));
        jButtonBin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonBin.setText("BIN");
        jButtonBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBinActionPerformed(evt);
            }
        });

        jButtonRound.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonRound.setText("...0");
        jButtonRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoundActionPerformed(evt);
            }
        });

        jButtonRaiz.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonRaiz.setText("x√n");
        jButtonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizActionPerformed(evt);
            }
        });

        jButtonMul.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonMul.setText("x");
        jButtonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMulActionPerformed(evt);
            }
        });

        jButtonDiv.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonDiv.setText("/");
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });

        jButtonC.setBackground(new java.awt.Color(153, 153, 153));
        jButtonC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonRad.setBackground(new java.awt.Color(153, 153, 153));
        jButtonRad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonRad.setText("RAD");
        jButtonRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRadActionPerformed(evt);
            }
        });

        jButtonEq.setBackground(new java.awt.Color(153, 153, 153));
        jButtonEq.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonEq.setText("=");
        jButtonEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("   Calculadora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jButtonN7.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonN7.setText("7");
        jButtonN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN7ActionPerformed(evt);
            }
        });

        jTextField1.setText("0");

        jBack.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBack.setText("...");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        jMenuAjuda.setText("Ajuda");

        jMenuItemAjuda.setText("Como Usar");
        jMenuItemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAjuda);

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAjuda);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Confirmar");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonN7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPot, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSqr, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonN4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonN1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonN0, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDec, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButtonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonRad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonEq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCe, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonBin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonRound, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(txtResultado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1)))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtResultado)
                    .addComponent(jBack, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonN9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSqr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonN6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonN3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRound, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotActionPerformed
        op = "pot";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }

            txtResultado.setText("");
            jTextField1.setText(jTextField1.getText()+" ^ ");
        //}
    }//GEN-LAST:event_jButtonPotActionPerformed

    private void jButtonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiActionPerformed
        n1 = Math.PI;
        txtResultado.setText("");
        txtResultado.setText(txtResultado.getText()+n1);
        jTextField1.setText(jTextField1.getText()+"π");
    }//GEN-LAST:event_jButtonPiActionPerformed

    private void jButtonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinActionPerformed
        op = "sin";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        
        txtResultado.setText("");
        n3 = funct.Sin(n1);
        hist[histN] = n3;
        histN++;
        txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
        jTextField1.setText(jTextField1.getText()+" SIN("+n1+")");
        e = true;

    }//GEN-LAST:event_jButtonSinActionPerformed

    private void jButtonDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecActionPerformed
        type = "dec";
    }//GEN-LAST:event_jButtonDecActionPerformed

    private void jButtonBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBinActionPerformed
        op = "bin";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        jTextField1.setText(jTextField1.getText()+" BIN ");
        n3 = funct.Bin(n1);
        txtResultado.setText(txtResultado.getText()+n3);
        hist[histN] = n3;
        histN++;
        e = true;
    }//GEN-LAST:event_jButtonBinActionPerformed

    private void jButtonRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRadActionPerformed
        type = "rad";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        n1 = Math.toRadians(n1);
        txtResultado.setText("");
        txtResultado.setText(txtResultado.getText()+n1);
        jTextField1.setText(jTextField1.getText()+" Rad("+n1+"°)");
        hist[histN] = n1;
        histN++;
        e = true;
    }//GEN-LAST:event_jButtonRadActionPerformed

    private void jButtonN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN5ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"5");
        //jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_jButtonN5ActionPerformed

    private void jButtonN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN0ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"0");
        //jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_jButtonN0ActionPerformed

    private void jButtonN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN1ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"1");
        //jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_jButtonN1ActionPerformed

    private void jButtonN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN2ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"2");
        //jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_jButtonN2ActionPerformed

    private void jButtonN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN3ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"3");
        //jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_jButtonN3ActionPerformed

    private void jButtonN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN4ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"4");
        //jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_jButtonN4ActionPerformed

    private void jButtonN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN6ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"6");
       //jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_jButtonN6ActionPerformed

    private void jButtonN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN7ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"7");
        //jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_jButtonN7ActionPerformed

    private void jButtonN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN9ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"9");
        //jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_jButtonN9ActionPerformed

    private void jButtonN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN8ActionPerformed
        if(ini == true){
            jTextField1.setText("");
            ini = false;
        }
        if(e == true){
            txtResultado.setText("");
            e = false;
        }
        txtResultado.setText(txtResultado.getText()+"8");
        //jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_jButtonN8ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        if(ini == true){
            jTextField1.setText("");
            e = false;
            ini = false;
        }
        txtResultado.setText(txtResultado.getText()+".");
        //jTextField1.setText(jTextField1.getText()+".");
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        op = "soma";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        jTextField1.setText(jTextField1.getText()+" "+n1+" + ");
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        op = "sub";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        jTextField1.setText(jTextField1.getText()+" "+n1+" - ");
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jButtonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMulActionPerformed
        op = "mul";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        jTextField1.setText(jTextField1.getText()+" "+n1+" x ");
    }//GEN-LAST:event_jButtonMulActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        op = "div";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        jTextField1.setText(jTextField1.getText()+" "+n1+" / ");
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButtonRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoundActionPerformed
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        n1 = Math.ceil(n1);
        hist[histN] = n1;
        histN++;
        txtResultado.setText(txtResultado.getText()+" "+n1);
        jTextField1.setText(jTextField1.getText()+" "+n1);
        e = true;
    }//GEN-LAST:event_jButtonRoundActionPerformed

    private void jButtonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizActionPerformed
        op = "sqrN";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        jTextField1.setText(" "+n1+" √"+jTextField1.getText());
    }//GEN-LAST:event_jButtonRaizActionPerformed

    private void jButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoActionPerformed
        op = "no";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        n1 = funct.Negative(n1);
        txtResultado.setText(txtResultado.getText()+n1);
        hist[histN] = n1;
        histN++;
        jTextField1.setText(" "+jTextField1.getText()+n1);
        e = true;
    }//GEN-LAST:event_jButtonNoActionPerformed

    private void jButtonPorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorcActionPerformed
        op = "porc";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        jTextField1.setText(jTextField1.getText()+" "+n1+" % ");
    }//GEN-LAST:event_jButtonPorcActionPerformed

    private void jButtonFatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFatActionPerformed
        op = "fat";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        n3 = funct.Fat(n1);
        txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
        hist[histN] = n3;
        histN++;
        jTextField1.setText(jTextField1.getText()+" "+n1+"!");
        e = true;
    }//GEN-LAST:event_jButtonFatActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        op = "log";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        n3 = funct.Log(n1);
        txtResultado.setText(txtResultado.getText()+n3);
        hist[histN] = n3;
        histN++;
        jTextField1.setText(jTextField1.getText()+" log("+n1+")");
        e = true;
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        op = "mod";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        jTextField1.setText(jTextField1.getText()+" "+n1+" MOD ");
    }//GEN-LAST:event_jButtonModActionPerformed

    private void jButtonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosActionPerformed
        op = "cos";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        n3 = funct.Cos(n1);
        hist[histN] = n3;
        histN++;
        txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
        jTextField1.setText(jTextField1.getText()+" COS("+n1+")");
        e = true;
    }//GEN-LAST:event_jButtonCosActionPerformed

    private void jButtonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanActionPerformed
        op = "tan";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        n3 = funct.Tan(n1);
        hist[histN] = n3;
        histN++;
        txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
        jTextField1.setText(jTextField1.getText()+" TAN("+n1+")");
        e = true;
    }//GEN-LAST:event_jButtonTanActionPerformed

    private void jButtonSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSqrActionPerformed
        op = "sqr";
        aux = txtResultado.getText();
        
        try {
            n1 = Double.parseDouble(aux);
        } catch (NumberFormatException e) {
            //Se chegou aqui, não é um double!
            JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
            txtResultado.setText("");
            return;
        }
        txtResultado.setText("");
        n3 = funct.Sqr(n1);
        
        txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
        hist[histN] = n3;
        histN++;
        jTextField1.setText(" √"+jTextField1.getText()+n1);
        e = true;
    }//GEN-LAST:event_jButtonSqrActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        txtResultado.setText("");
        txtResultado.setText(txtResultado.getText()+"0");
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCeActionPerformed
        txtResultado.setText("");
        jTextField1.setText("");
        txtResultado.setText(txtResultado.getText()+"0");
    }//GEN-LAST:event_jButtonCeActionPerformed

    private void jButtonEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqActionPerformed
        if(op == "soma"){
            aux = txtResultado.getText();
        
            try {
                n2 = Double.parseDouble(aux);
            } catch (NumberFormatException e) {
                //Se chegou aqui, não é um double!
                JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
                txtResultado.setText("");
                return;
            }
            txtResultado.setText("");
            n3 = funct.Soma(n1, n2);
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
            hist[histN] = n3;
            histN++;
            jTextField1.setText(jTextField1.getText()+n2);
            e = true;
        }
        if(op == "sub"){
            try {
                n2 = Double.parseDouble(aux);
            } catch (NumberFormatException e) {
                //Se chegou aqui, não é um double!
                JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
                txtResultado.setText("");
                return;
            }
            txtResultado.setText("");
            n3 = funct.Sub(n1, n2);
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
            hist[histN] = n3;
            histN++;
            jTextField1.setText(jTextField1.getText()+n2);
            e = true;
        }
        if(op == "mul"){
            try {
                n2 = Double.parseDouble(aux);
            } catch (NumberFormatException e) {
                //Se chegou aqui, não é um double!
                JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
                txtResultado.setText("");
                return;
            }
            txtResultado.setText("");
            n3 = funct.Mul(n1, n2);
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
            hist[histN] = n3;
            histN++;
            jTextField1.setText(jTextField1.getText()+n2);
            e = true;
        }
        if(op == "div"){
            try {
                n2 = Double.parseDouble(aux);
            } catch (NumberFormatException e) {
                //Se chegou aqui, não é um double!
                JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
                txtResultado.setText("");
                return;
            }
            txtResultado.setText("");
            n3 = funct.Div(n1, n2);
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
            hist[histN] = n3;
            histN++;
            jTextField1.setText(jTextField1.getText()+n2);
            e = true;
        }
        if(op == "pot"){
            try {
                n2 = Double.parseDouble(aux);
            } catch (NumberFormatException e) {
                //Se chegou aqui, não é um double!
                JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
                txtResultado.setText("");
                return;
            }
            txtResultado.setText("");
            n3 = funct.Pot(n1, n2);
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
            hist[histN] = n3;
            histN++;
            jTextField1.setText(jTextField1.getText()+n2);
            e = true;
        }
        if(op == "sqr"){
            txtResultado.setText("");
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
            jTextField1.setText(jTextField1.getText()+n2);
        }
        if(op == "sqrN"){
            try {
                n2 = Double.parseDouble(aux);
            } catch (NumberFormatException e) {
                //Se chegou aqui, não é um double!
                JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
                txtResultado.setText("");
                return;
            }
            txtResultado.setText("");
            n3 = funct.SqrN(n1, n2);
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
            hist[histN] = n3;
            histN++;
            jTextField1.setText(n1+" √"+jTextField1.getText()+n2);
            e = true;
        }
        if(op == "fat"){
            txtResultado.setText("");
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
        }
        if(op == "mod"){
            try {
                n2 = Double.parseDouble(aux);
            } catch (NumberFormatException e) {
                //Se chegou aqui, não é um double!
                JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
                txtResultado.setText("");
                return;
            }
            txtResultado.setText("");
            n3 = funct.Mod(n1, n2);
            hist[histN] = n3;
            histN++;
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3));
            jTextField1.setText(jTextField1.getText()+n2);
            e = true;
        }
        if(op == "log"){
            txtResultado.setText("");
            txtResultado.setText(txtResultado.getText()+n3);
        }
        if(op == "porc"){
            try {
                n2 = Double.parseDouble(aux);
            } catch (NumberFormatException e) {
                //Se chegou aqui, não é um double!
                JOptionPane.showMessageDialog(new JFrame(), "Nao é um numero!\n");
                txtResultado.setText("");
                return;
            }
            txtResultado.setText("");
            n3 = funct.Porc(n1, n2);
            txtResultado.setText(txtResultado.getText()+String.valueOf(n3)+"%");
            hist[histN] = n3;
            histN++;
            jTextField1.setText(jTextField1.getText()+n2);
        }
        if(op == "sin"){
            txtResultado.setText("");
            txtResultado.setText(txtResultado.getText()+n3);
        }
        if(op == "cos"){
            txtResultado.setText("");
            txtResultado.setText(txtResultado.getText()+n3);
        }
        if(op == "tan"){
            txtResultado.setText("");
            txtResultado.setText(txtResultado.getText()+n3);
        }
        if(op == "none"){
            txtResultado.setText("");
        }
    }//GEN-LAST:event_jButtonEqActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        txtResultado.setText("");
        txtResultado.setText(txtResultado.getText()+" "+hist[histN-1]);
        histN--;
    }//GEN-LAST:event_jBackActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        setTitle("Sair");
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaActionPerformed
        setTitle("Como Usar");
        JOptionPane.showMessageDialog(CalcForm.this,
                         "Sobre:\n"+
                         "Esta Calculadora permite a realização de cálculos.\n" +
                         "Para executar as funcoes: digite o valor desejado ou clique no numero,\n" +
                         "em seguida, clique na função desejada e, caso necessario, digite o outro\n" +
                         "valor. E ao finalizar e iniciar um novo calculo, clique em C ou CE para\n " +
                         "limpar a tela. Para ver resultados anteriores, clique em [...]\n\n"+
                         "Atencao:\n"+
                         "      - Nao utilize letras\n"+
                         "      - Digite somente numeros no teclado ou negacao (-)\n"+
                         "      - Nao utilize sinais desnecessarios\n\n"
                         , "Como Usar", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItemAjudaActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        setTitle("Sobre");
        JOptionPane.showMessageDialog(this,
                         "Autores: Leonardo Coelho\n"+ 
                                  "Rodrigo Barbosa\n\n" +
                         "Java versao: 1.8.0\n" +
                         "IDE Utilizada: NetBeans IDE 8.2", "Sobre", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcForm().setVisible(true);
            }
        });
    }
    
    public void actionPerformed(ActionEvent x){
        if(x.getSource().equals(jMenuAjuda)){
            JOptionPane.showMessageDialog(CalcForm.this,
                         "Esta Calculadora permite a realização de cálculos\n" +
                         "simples, como fazer as 4 operações básicas, obter\n" +
                         "Raiz, Seno, Cosseno, Logaritmo, Inverso, Quadrado\n" +
                         "de um número.", "Ajuda", JOptionPane.PLAIN_MESSAGE);
        }
        if(x.getSource().equals(jMenuSair)){
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JButton jButtonBin;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCe;
    private javax.swing.JButton jButtonCos;
    private javax.swing.JButton jButtonDec;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEq;
    private javax.swing.JButton jButtonFat;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonMul;
    private javax.swing.JButton jButtonN0;
    private javax.swing.JButton jButtonN1;
    private javax.swing.JButton jButtonN2;
    private javax.swing.JButton jButtonN3;
    private javax.swing.JButton jButtonN4;
    private javax.swing.JButton jButtonN5;
    private javax.swing.JButton jButtonN6;
    private javax.swing.JButton jButtonN7;
    private javax.swing.JButton jButtonN8;
    private javax.swing.JButton jButtonN9;
    private javax.swing.JButton jButtonNo;
    private javax.swing.JButton jButtonPi;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPorc;
    private javax.swing.JButton jButtonPot;
    private javax.swing.JButton jButtonRad;
    private javax.swing.JButton jButtonRaiz;
    private javax.swing.JButton jButtonRound;
    private javax.swing.JButton jButtonSin;
    private javax.swing.JButton jButtonSqr;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JButton jButtonTan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAjuda;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
